### ISSUE TITLE
Eliminate the outline

### ISSUE THREAD

**Issue by sungwoncho** [aaronshaf/react-toggle#45]
_Version_
- react-toggle 2.1.0
- React 15.1.0.
- Chrome 51.0.2704.103

When I interact with react-toggle, the circle has an outline and it's weird from the user's point of view.

![react-toggle](https://cloud.githubusercontent.com/assets/8265228/16607186/dd25e8ee-4381-11e6-8bf1-15ffc522aefb.png)

I tried to put `outline: none` in DOM elements rendrered by react-toggle, but could not make it disappear. It shows when `.react-toggle` is `:active`. Any ideas on how to hide it? Happy to do a PR.

**Comment by claydiffrient** [comment]
@sungwoncho Thanks for filing the issue, but I don't think this is something we'd consider at this time.  The outline is essential for the accessibility of the component for people who only use the keyboard to navigate around the site.  For more details about that checkout http://www.outlinenone.com/

**Comment by sungwoncho** [comment]
Thanks for the link. Closing.

**Comment by maslick** [comment]
@sungwoncho how did you solve it?

**Comment by maslick** [comment]
This worked for me:
```css
/* React toggle: Disable box-shadow */
.react-toggle--focus .react-toggle-thumb {
  -webkit-box-shadow: none !important;
  -moz-box-shadow: none !important;
  box-shadow: none !important;
}

.react-toggle:active:not(.react-toggle--disabled) .react-toggle-thumb {
  -webkit-box-shadow: none !important;
  -moz-box-shadow: none !important;
  box-shadow: none !important;
}
```
